title: Qmio OpenPulse course
author: Alfredo Chavert Sancho
theme: minima
markdown: kramdown
execute:
  execute_notebooks: off
repository:
  url: https://github.com/achavert/qmio-openpulse 
  branch: main 


