title: Qmio pulse-level control ðŸš§ under development ðŸš§
description: Pulse-level control course and OpenPulse documentation for Qmio
author: Alfredo Chavert Sancho
theme: minima

 
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
   
execute:
  execute_notebooks: off

repository:
  url: https://github.com/achavert/qmio-openpulse 
  branch: main 

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  notebooks:
    output: true

defaults:
  - scope:
      path: "content"
    values:
      layout: default

exclude:
  - tests
  - notebooks
  - README.md
